dist: focal
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test      
    packages:
      - cmake
      - g++-9
      - build-essential
      - ninja-build
      - qt5-default

script:
  - cmake --version
  - ninja -v
  - bootstrap.sh
  - cd build
  - ninja
