dist: focal
language: cpp
compiler: gcc

branches:
  only:
  - stable

addons:
  apt:
    packages:
      - cmake
      - g++-9
      - build-essential
      - ninja-build
      - qt5-default 

# only build when a tag is present
if: tag IS present

script:
  - cmake --version
  - ninja --version
  - ./bootstrap.sh
  - cd build
  - ninja
