dist: focal
language: cpp
compiler: gcc

branches:
  only:
  - stable

addons:
  apt:
    packages:
      - cmake
      - g++-9
      - build-essential
      - ninja-build
      - qt5-default 
      - libboost-test-dev
      - libboost-filesystem-dev

script:
  - cmake --version
  - ninja --version
  - ./bootstrap.sh
  - cd build
  - ninja
  - ctest -V
