## SPDX-FileCopyrightText: 2021-2022 Niels Moseley <asicsforthemasses@gmail.com>
##
## SPDX-License-Identifier: GPL-3.0-only

os: Visual Studio 2022

install:
  - dir C:\Qt
  - dir C:\Qt\5.15
  - dir C:\Qt\5.15\msvc2019_64
  - set QTDIR=C:\Qt\5.15\msvc2019_64\bin
  - set BOOST_ROOT=C:\Libraries\boost_1_77_0
  - set PATH=%QTDIR%;%BOOST_ROOT%;%PATH%;
  - set CMAKE_PREFIX_PATH=%QTDIR%;%BOOST_ROOT%;%CMAKE_PREFIX_PATH%

before_build:

  - mkdir build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "Visual Studio 17 2022" -A x64 ..
  - if "%PLATFORM%"=="Win32" cmake -G "Visual Studio 17 2022" -A Win32 ..

build:
  project: build\ALL_BUILD.vcxproj

after_build:
#- ps: |
#    Push-AppveyorArtifact $env:CONFIGURATION\openpnp-capture.dll -FileName openpnp-capture_$env:PLATFORM.dll
#    Push-AppveyorArtifact win\tests\$env:CONFIGURATION\openpnp-capture-test.exe -FileName openpnp-capture-test_$env:PLATFORM.exe

platform:
  #- Win32
  - x64

configuration:
  #- Debug
  - Release

#deploy:
#  description: 'Auto generated release.'
#  provider: GitHub
#  force_update: true
#  auth_token:
#    secure: 3v/KanZhhv0cW/IcjK45UOUXD3RoSx9doiNdvMHxGpVro/KD6eKQ23U0oHIgnZl0
#  on:
#    appveyor_repo_tag: true
#    configuration: Release
