## SPDX-FileCopyrightText: 2021-2022 Niels Moseley <asicsforthemasses@gmail.com>
##
## SPDX-License-Identifier: GPL-3.0-only

os: Visual Studio 2022

cache:
  - c:\Eigen3\

install:
  - cmd: if not exist c:\Eigen3 (
            curl -L -o eigen-3.4.0.tar.gz https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz &&
            cmake -E tar zxf eigen-3.4.0.tar.gz &&
            dir &&
            cd eigen-3.4.0 &&
            dir &&
            mkdir build &&
            cd build &&
            cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="c:\Eigen3" .. &&
            cmake --build . --target install --config Release &&
            cd ..\.     
          ) else (echo Using cached Eigen3)

before_build:

  - mkdir build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "Visual Studio 17 2022" -A x64 ..
  - if "%PLATFORM%"=="Win32" cmake -G "Visual Studio 17 2022" -A Win32 ..

build:
  project: build\ALL_BUILD.vcxproj

after_build:
#- ps: |
#    Push-AppveyorArtifact $env:CONFIGURATION\openpnp-capture.dll -FileName openpnp-capture_$env:PLATFORM.dll
#    Push-AppveyorArtifact win\tests\$env:CONFIGURATION\openpnp-capture-test.exe -FileName openpnp-capture-test_$env:PLATFORM.exe

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

#deploy:
#  description: 'Auto generated release.'
#  provider: GitHub
#  force_update: true
#  auth_token:
#    secure: 3v/KanZhhv0cW/IcjK45UOUXD3RoSx9doiNdvMHxGpVro/KD6eKQ23U0oHIgnZl0
#  on:
#    appveyor_repo_tag: true
#    configuration: Release
